### ISSUE TITLE
Hide content container with css

### ISSUE THREAD

**Issue by markusahlstrand** [sesamyab/wordpress-sesamy#11]
When the content-container web components is rendered in embed mode it flashes the locked content and if the user disables javascript both the unlocked and locked content is visible. As it's technically is locked in javascript the only solution we can think of is to add a display:none tag to the locked content slot.

When the content is unlocked it is copied outside the content-container so there's not really any case when the content inside the content-container should be rendered.

We have this solution in place in our demo-project and it seems to work well:

```
    <style>
      sesamy-content-container {
        display: none;
      }
```

**Comment by jstensved** [comment]
Added a constant, if `SESAMY_DEV_API` is defined in code the dev endpoint will be used
