### ISSUE TITLE
Render meta tags for categories and tags

### ISSUE THREAD

**Issue by markusahlstrand** [sesamyab/wordpress-sesamy#16]
We started ingesting the category and tags metatags. Is there a good default to map these to something in wordpress or would you need to configure it in the admin section.

More info about the indexed tags here:
https://docs.sesamy.com/integrations/fC87H8i3buXbLMw8Nv81EG/meta-tags/7eDaJLfNQYy8atRPpKZvyv

**Comment by PradeepWeb77** [comment]
WordPress don't provide metatags for category and tags on post page. 

We need to add code to render category and tags metatags. I have gone through metatags documentation
https://docs.sesamy.com/integrations/fC87H8i3buXbLMw8Nv81EG/meta-tags/7eDaJLfNQYy8atRPpKZvyv

I can develop a code which will add category and tags metatags.

**Comment by markusahlstrand** [comment]
Hi, it would be great if we could add those tags. Then our indexer will pick them up.

**Comment by PradeepWeb77** [comment]
Sure, I will work on this monday
