### ISSUE TITLE
Support page-breaks instead of excerpt as previews for locked articles.

### ISSUE THREAD

**Issue by markusahlstrand** [sesamyab/wordpress-sesamy#18]

**Comment by jstensved** [comment]
It may be useful to know that WordPress has two similar blocks in the Gutenberg editor; "More" and "Read more". The "more" is the old block used to cut content.

The plugin will look at the "more" block as that is supported by the built-in function `get_extended` that will handle cutting the content.

Also adding a filter called `sesamy_paywall_preview` that anyone can use to make their own previews for special cases. 

![image](https://user-images.githubusercontent.com/2311151/221042953-a199589a-60aa-4336-b6ee-b90068ff49d0.png)

Used in content like this:

![image](https://user-images.githubusercontent.com/2311151/221042875-b1c9f7c3-a5e8-4f68-a7ed-d7a3f919d390.png)

**Comment by jstensved** [comment]
The paywall will try to create a preview in the following order now:

a) Content before more tag
b) Manually written excerpt
c) Automatically generated excerpt

a is using `get_extended` and b/c is using the `get_the_excerpt` functions in WordPress
