### ISSUE TITLE
The subscribe button isn't linking to the url of the subscription

### ISSUE THREAD

**Issue by markusahlstrand** [sesamyab/wordpress-sesamy#25]
It seems like the pass currently only is the slug of the subscription, but in order for the checkout to find the metadata for the subscription it needs to be the full url.

So, for the test website the pass is rendered like this on an artitlce:
```
<meta property="sesamy:pass" content="subscribe" />
```

But is would need to be added like this:
```
<meta property="sesamy:pass" content="https://www.sesamy.dev/wp-json/sesamy/v1/passes/2" />
```

Ideally we would like to use the slug instead of the id, as we don't want the url of the pass to change if there's an update. Is this possible? I looks like we could do: https://www.sesamy.dev/wp-json/sesamy/v1/passes?id=subscribe. It returns an array which we might currently not support but should be doable. Is there a better way? 

The same goes for the subscribe button that needs to use the metadata link for the pass when creating the checkout link, rather than the public url of the pass.

**Comment by jstensved** [comment]
Endpoint for passes is as follows:

List:  https://www.sesamy.dev/wp-json/sesamy/v1/passes
Details: https://www.sesamy.dev/wp-json/sesamy/v1/passes/pass-name

See https://github.com/sesamyab/wordpress-sesamy/commit/1411cc706051d1724970c73adb12fd3dd898d746 for details
