### ISSUE TITLE
Updated json structure for passes

### ISSUE THREAD

**Issue by markusahlstrand** [sesamyab/wordpress-sesamy#26]
We need to do a small change of the current structure of the json returned. 

Currently it looks like this:
```
[
{
"id": "prenumeration",
"title": "Prenumeration",
"description": "",
"price": "99",
"currency": "SEK",
"image": null,
"url": "",
"item_src": "https://staging.iconmagazine.se/wp-json/sesamy/v1/passes/52",
"period": "monthly",
"time": "1",
"product_type": "RECURRING"
}
]
```

The product type needs to be PASS and the recurring information should be passed as "payment_type":

```
[
{
"id": "prenumeration",
"title": "Prenumeration",
"description": "",
"price": "99",
"currency": "SEK",
"image": null,
"url": "",
"item_src": "https://staging.iconmagazine.se/wp-json/sesamy/v1/passes?id=prenumeration",
"period": "monthly",
"time": "1",
"product_type": "PASS",
"payment_type": "RECURRING"
}
]
```

**Comment by jstensved** [comment]
Url structure for item_src is described in https://github.com/sesamyab/wordpress-sesamy/issues/26 following regular rest-api naming convention with appending /id after listing URL for retrieving a specific item
